const perform = (z, bundle) => {
  const options = {
    url: `https://smartsysdemo.vendhq.com/api/register_sales/${bundle.inputData.id}`,
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: `Bearer ${bundle.authData.access_token}`,
    },
    params: {
      id: bundle.inputData.id,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;

    // You can do any parsing you need for results here before returning them

    return results.register_sales;
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'id',
        label: 'Sale Id',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      id: '0a6f6e36-8bc1-11ea-f3d6-f740d499d430',
      source: 'USER',
      source_id: '',
      register_id: '0a6f6e36-8be2-11ea-f3d6-f138758cc760',
      market_id: '7',
      customer_name: 'Ashley Starke 2970 ',
      customer: {
        id: '0a6f6e36-8bc1-11ea-f3d6-f740d1e02f3c',
        name: 'Ashley Starke 2970 ',
        customer_code: 'Ashley Starke 2970-JY9M',
        customer_group_id: '0a6f6e36-8be2-11ea-f3d6-f13875728dc1',
        customer_group_name: 'All Customers',
        first_name: 'Ashley Starke 2970',
        last_name: '',
        company_name: '',
        phone: '',
        mobile: '0736258708',
        fax: '',
        email: 'ashley.starke@matasa.co.za',
        do_not_email: '0',
        twitter: '',
        website: '',
        physical_address1: '',
        physical_address2: '',
        physical_suburb: '',
        physical_city: '',
        physical_postcode: '',
        physical_state: '',
        physical_country_id: '',
        postal_address1: '',
        postal_address2: '',
        postal_suburb: '',
        postal_city: '',
        postal_postcode: '',
        postal_state: '',
        postal_country_id: '',
        updated_at: '2020-09-15 10:47:15',
        deleted_at: '',
        balance: '0.000',
        year_to_date: '0.00000',
        date_of_birth: '',
        sex: '',
        note: '',
        contact: {
          company_name: '',
          phone: '',
          email: 'ashley.starke@matasa.co.za',
        },
        custom_field_1: '',
        custom_field_2: '',
        custom_field_3: '',
        custom_field_4: '',
      },
      user_id: '0a6f6e36-8be2-11ea-f3d6-f138759106b4',
      user_name: 'accounts@we-make-sense.net',
      sale_date: '2020-10-04 00:00:00',
      created_at: '2020-09-15 10:47:20',
      updated_at: '2020-09-15 10:47:20',
      total_price: 155,
      total_cost: 24,
      total_tax: 37,
      note: 'Booking form submitted online on 15-09-2020- Total R155',
      status: 'SAVED',
      short_code: 'qhviwp',
      invoice_number: 'test 2',
      accounts_transaction_id: '',
      return_for: '',
      register_sale_products: [
        {
          id: '0a6f6e36-8bc1-11ea-f3d6-f740d49edf3f',
          product_id: '0a6f6e36-8bc1-11ea-f3d6-f7370c8d344d',
          register_id: '0a6f6e36-8be2-11ea-f3d6-f138758cc760',
          sequence: '0',
          handle: 'braaiarea',
          sku: '10025',
          name: 'BRAAI AREA PER PERSON',
          quantity: 6,
          price: 20,
          cost: 0,
          price_set: 0,
          discount: 0,
          loyalty_value: 0,
          tax: 6,
          tax_id: '0a6f6e36-8bc1-11ea-f3d6-f138c589d1ed',
          tax_name: 'Normal Tax Rate',
          tax_rate: 0.15,
          tax_total: 36,
          price_total: 120,
          display_retail_price_tax_inclusive: '1',
          status: 'SAVED',
          attributes: [{ name: 'line_note', value: '' }],
        },
        {
          id: '0a6f6e36-8bc1-11ea-f3d6-f740d4a0957b',
          product_id: '0a6f6e36-8bc1-11ea-f3d6-f7370bcb216d',
          register_id: '0a6f6e36-8be2-11ea-f3d6-f138758cc760',
          sequence: '0',
          handle: 'charcoal',
          sku: '10214',
          name: 'CHARCOAL',
          quantity: 1,
          price: 35,
          cost: 24,
          price_set: 0,
          discount: 0,
          loyalty_value: 0,
          tax: 1,
          tax_id: '0a6f6e36-8bc1-11ea-f3d6-f138c589d1ed',
          tax_name: 'Normal Tax Rate',
          tax_rate: 0.15,
          tax_total: 1,
          price_total: 35,
          display_retail_price_tax_inclusive: '1',
          status: 'SAVED',
          attributes: [{ name: 'line_note', value: '' }],
        },
      ],
      register_sale_payments: [],
      customer_id: '0a6f6e36-8bc1-11ea-f3d6-f740d1e02f3c',
      taxes: [
        {
          tax: 37,
          name: 'Normal Tax Rate',
          rate: 0.15,
          id: 'c589c17f-f138-11ea-93d6-0a6f6e368be2',
        },
      ],
      tax_name: 'Normal Tax Rate',
      totals: {
        total_tax: 37,
        total_price: 155,
        total_payment: 0,
        total_to_pay: 192,
      },
    },
    outputFields: [
      { key: 'id' },
      { key: 'source' },
      { key: 'source_id' },
      { key: 'register_id' },
      { key: 'market_id' },
      { key: 'customer_name' },
      { key: 'customer__id' },
      { key: 'customer__name' },
      { key: 'customer__customer_code' },
      { key: 'customer__customer_group_id' },
      { key: 'customer__customer_group_name' },
      { key: 'customer__first_name' },
      { key: 'customer__last_name' },
      { key: 'customer__company_name' },
      { key: 'customer__phone' },
      { key: 'customer__mobile' },
      { key: 'customer__fax' },
      { key: 'customer__email' },
      { key: 'customer__do_not_email' },
      { key: 'customer__twitter' },
      { key: 'customer__website' },
      { key: 'customer__physical_address1' },
      { key: 'customer__physical_address2' },
      { key: 'customer__physical_suburb' },
      { key: 'customer__physical_city' },
      { key: 'customer__physical_postcode' },
      { key: 'customer__physical_state' },
      { key: 'customer__physical_country_id' },
      { key: 'customer__postal_address1' },
      { key: 'customer__postal_address2' },
      { key: 'customer__postal_suburb' },
      { key: 'customer__postal_city' },
      { key: 'customer__postal_postcode' },
      { key: 'customer__postal_state' },
      { key: 'customer__postal_country_id' },
      { key: 'customer__updated_at' },
      { key: 'customer__deleted_at' },
      { key: 'customer__balance' },
      { key: 'customer__year_to_date' },
      { key: 'customer__date_of_birth' },
      { key: 'customer__sex' },
      { key: 'customer__note' },
      { key: 'customer__contact__company_name' },
      { key: 'customer__contact__phone' },
      { key: 'customer__contact__email' },
      { key: 'customer__custom_field_1' },
      { key: 'customer__custom_field_2' },
      { key: 'customer__custom_field_3' },
      { key: 'customer__custom_field_4' },
      { key: 'user_id' },
      { key: 'user_name' },
      { key: 'sale_date' },
      { key: 'created_at' },
      { key: 'updated_at' },
      { key: 'total_price' },
      { key: 'total_cost' },
      { key: 'total_tax' },
      { key: 'note' },
      { key: 'status' },
      { key: 'short_code' },
      { key: 'invoice_number' },
      { key: 'accounts_transaction_id' },
      { key: 'return_for' },
      { key: 'register_sale_products[]id' },
      { key: 'register_sale_products[]product_id' },
      { key: 'register_sale_products[]register_id' },
      { key: 'register_sale_products[]sequence' },
      { key: 'register_sale_products[]handle' },
      { key: 'register_sale_products[]sku' },
      { key: 'register_sale_products[]name' },
      { key: 'register_sale_products[]quantity' },
      { key: 'register_sale_products[]price' },
      { key: 'register_sale_products[]cost' },
      { key: 'register_sale_products[]price_set' },
      { key: 'register_sale_products[]discount' },
      { key: 'register_sale_products[]loyalty_value' },
      { key: 'register_sale_products[]tax' },
      { key: 'register_sale_products[]tax_id' },
      { key: 'register_sale_products[]tax_name' },
      { key: 'register_sale_products[]tax_rate' },
      { key: 'register_sale_products[]tax_total' },
      { key: 'register_sale_products[]price_total' },
      { key: 'register_sale_products[]display_retail_price_tax_inclusive' },
      { key: 'register_sale_products[]status' },
      { key: 'register_sale_products[]attributes[]name' },
      { key: 'register_sale_products[]attributes[]value' },
      { key: 'customer_id' },
      { key: 'taxes[]tax' },
      { key: 'taxes[]name' },
      { key: 'taxes[]rate' },
      { key: 'taxes[]id' },
      { key: 'tax_name' },
      { key: 'totals__total_tax' },
      { key: 'totals__total_price' },
      { key: 'totals__total_payment' },
      { key: 'totals__total_to_pay' },
    ],
  },
  key: 'find_sale',
  noun: 'sale',
  display: {
    label: 'Find Sale',
    description: 'To find sale in vend based upon sale id',
    hidden: false,
    important: true,
  },
};
